{% set name = "sagemaker-tensorflow-extensions" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2b433eb3de4646760b204561414607d0b2127c8703807f615b1cce7ff4443967
  patches:
    - cxx.patch
    
build:
  number: 0
  skip: True  # [win]
  script:
    - ls
    - {{ PYTHON }} -m pip install . -vv

requirements:
  run_constrained:
    - glibc >=2.17
  build:
    - {{ compiler('cxx') }}
    - cmake
    - tensorflow <=1.12
  host:
    - pip
    - python <=3.6
    - tensorflow <=1.12
    - sagemaker-python-sdk
  run:
    - python <=3.6
    - tensorflow <=1.12
    - sagemaker-python-sdk

test:
  requires:
    - tox
    - flake8
    - pytest
    - mock
    - docker-compose
    - boto3
    - sagemaker-python-sdk
  imports:
    - sagemaker_tensorflow

about:
  home: https://github.com/aws/sagemaker-tensorflow-extensions
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "SageMaker TensorFlow Containers is an open source library for making the TensorFlow framework run on Amazon SageMaker."
  doc_url: https://sagemaker.readthedocs.io/en/stable/using_tf.html
  dev_url: https://github.com/aws/sagemaker-tensorflow-extensions

extra:
  recipe-maintainers:
    - benhuff
    - oblute
