{% set name = "h3" %}
{% set version = "3.4.3" %}

package:
  name: {{ name|lower }}-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a292a5a63bcf535f0137141019f3defd21ad2fbd258dc8de587f921cf2c5b41d
  patches:
    - setup.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: True  # [py27]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - h3
  run:
    - python

test:
  imports:
    - h3

about:
  home: https://github.com/uber/h3-py.git
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Python bindings for H3, a hierarchical hexagonal geospatial indexing system developed by Uber Technologies
  dev_url: https://github.com/uber/h3-py.git

extra:
  recipe-maintainers:
    - benhuff
    - oblute
    - geoHeil
