{% set name = "pycuda" %}
{% set version = "2019.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ada56ce98a41f9f95fe18809f38afbae473a5c62d346cfa126a2d5477f24cc8a
  patches:
    - aksetup_fixes.patch

build:
  number: 0
  skip: True  # [py2k or osx]
  script:
    # CUDA 10.1 moves some headers to `/usr/include`
    # So add that location last in the header search paths
    - export CFLAGS="${CFLAGS} -I/usr/include"
    - export CPPFLAGS="${CPPFLAGS} -I/usr/include"
    - export CXXFLAGS="${CXXFLAGS} -I/usr/include"
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cudnn
    - cudatoolkit
  host:
    - pip
    - python >=3.6
    - numpy >=1.6
    - setuptools
    - cudnn
    - cudatoolkit
  run:
    - python >=3.6
    - appdirs >=1.4.0
    - decorator >=3.2.0
    - mako
    - pytools >=2011.2
    - numpy >=1.6

test:
  imports:
    - pycuda
    - pycuda.compyte
    - pycuda.gl
    - pycuda.sparse

about:
  home: http://mathema.tician.de/software/pycuda
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Python wrapper for Nvidia CUDA"
  doc_url: https://documen.tician.de/pycuda/
  dev_url: https://github.com/inducer/pycuda

extra:
  recipe-maintainers:
    - oblute