{% set name = "cockroachdb-go" %}
{% set version = "19.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://binaries.cockroachdb.com/cockroach-v{{ version }}.darwin-10.9-amd64.tgz  # [osx]
    sha256: 46e9b9517cfdcb2154ab43304b8daade4f8663bd852e6ff6d0f40eb36570e2b5  # [osx]
    url: https://binaries.cockroachdb.com/cockroach-v{{ version }}.linux-amd64.tgz  # [linux]
    sha256: 66f9f9819453efca62ef752f5bc93cc53d5c514856463dde0da231e22102d0f4  # [linux]

build:
  number: 0
  skip: True  # [win]
  binary_relocation: False
#  missing_dso_whitelist:
#    - '*'

test:
  commands:
    - cockroach version

about:
  home: https://www.cockroachlabs.com/
  license: OTHER
  license_file: LICENSE
  summary: 'CockroachDB - the open source, cloud-native SQL database.'
  doc_url: https://www.cockroachlabs.com/docs/stable/
  dev_url: https://github.com/cockroachdb/cockroach

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - benhuff
