{% set name = "differential-privacy" %}
{% set version = "0.1" %}

package:
  name: "google-{{ name|lower }}"
  version: {{ version }}

source:
  url: https://github.com/google/{{ name }}/archive/master.tar.gz
  sha256: ee3ee20fe61281e88337f2b1baee2fd322f7ae6aa28771972479ac93e57499dd
build:
  number: 0
  script_env:
    - LD_LIBRARY_PATH # [linux]
    - DYLD_LIBRARY_PATH # [osx]
  script:
    - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${PREFIX}/lib"
    - bazel build --linkopt="-lrt" differential_privacy/...
  skip: True  # [win]

requirements:
  build:
    - rules_foreign_cc
    - bazel >=0.24
    - {{ compiler('cxx') }}
    - readline
    - libgcc

  host:
    - python
    - pip
    - rules_foreign_cc
    - readline

  run:
    - python

test:
  commands:
    - exit 0

about:
  home: https://github.com/google/differential-privacy
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Algorithms that can be used to produce aggregate statistics over numeric data sets containing private or sensitive information'
  description: |
    All of these algorithms are suitable for research, experimental or production use cases.
    All of our code assume that each user contributes only a single row to each aggregation.
    Disclaimer: This is not an officially supported Google product.
  doc_url: https://github.com/google/differential-privacy
  dev_url: https://github.com/google/differential-privacy

extra:
  recipe-maintainers:
     - mwilson8
     - benhuff