{% set version = '0.76' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-readtext
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/readtext_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/readtext/readtext_{{ version }}.tar.gz
  sha256: 92d3335b7b19cd1cc8298615e28fb0174c6ef9410d3351567b2578a5c46ae9cc

build:
  merge_build_host: True  # [win]
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-antiword
    - r-data.table
    - r-digest
    - r-httr
    - r-jsonlite >=0.9.10
    - r-pdftools
    - r-readods
    - r-readxl
    - r-streamr
    - r-stringi
    - r-striprtf
    - r-tibble
    - r-xml2

  run:
    - r-base
    - r-antiword
    - r-data.table
    - r-digest
    - r-httr
    - r-jsonlite >=0.9.10
    - r-pdftools
    - r-readods
    - r-readxl
    - r-streamr
    - r-stringi
    - r-striprtf
    - r-tibble
    - r-xml2

test:
  commands:
    - $R -e "library('readtext')"           # [not win]
    - "\"%R%\" -e \"library('readtext')\""  # [win]

about:
  home: http://github.com/quanteda/readtext
  license: GPL-3
  summary: Functions for importing and handling text files and formatted text files with additional
    meta-data, such including '.csv', '.tab', '.json', '.xml', '.html', '.pdf', '.doc',
    '.docx', '.rtf', '.xls', '.xlsx', and others.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - oblute
    - benhuff

# The original CRAN metadata for this package was:

# Package: readtext
# Version: 0.76
# Type: Package
# Title: Import and Handling for Plain and Formatted Text Files
# Authors@R: c( person("Kenneth", "Benoit", email = "kbenoit@lse.ac.uk", role = c("aut", "cre", "cph")), person("Adam", "Obeng", email = "quanteda@binaryeagle.com", role = "aut"), person("Kohei", "Watanabe", email = "watanabe.kohei@gmail.com", role = "ctb"), person("Akitaka", "Matsuo", email = "a.matsuo@lse.ac.uk", role = "ctb"), person("Paul", "Nulty", email = "paul.nulty@gmail.com", role = "ctb"), person("Stefan", "Muller", email = "mullers@tcd.ie", role = "ctb"))
# Description: Functions for importing and handling text files and formatted text files with additional meta-data, such including '.csv', '.tab', '.json', '.xml', '.html', '.pdf', '.doc', '.docx', '.rtf', '.xls', '.xlsx', and others.
# License: GPL-3
# Depends: R (>= 3.1)
# Imports: antiword, data.table, digest, httr, jsonlite (>= 0.9.10), pdftools, readODS, readxl, streamR, stringi, striprtf, tibble, xml2, utils
# Suggests: knitr, pkgload, rmarkdown, quanteda (>= 1.1.0), testthat
# URL: http://github.com/quanteda/readtext
# Encoding: UTF-8
# BugReports: https://github.com/quanteda/readtext/issues
# LazyData: TRUE
# VignetteBuilder: knitr
# RoxygenNote: 7.0.2
# NeedsCompilation: no
# Packaged: 2020-03-04 01:47:22 UTC; kbenoit
# Author: Kenneth Benoit [aut, cre, cph], Adam Obeng [aut], Kohei Watanabe [ctb], Akitaka Matsuo [ctb], Paul Nulty [ctb], Stefan Muller [ctb]
# Maintainer: Kenneth Benoit <kbenoit@lse.ac.uk>
# Repository: CRAN
# Date/Publication: 2020-03-04 05:50:02 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
